# commit to be tagged for the new release
commit = "HEAD"

project_name = "extensions-validator"
github_repo = "siderolabs/extensions-validator"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
